apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-api

  template:

    metadata:
      labels:
        app: employee-api

    spec:

      containers:

      - name: employee-api

        image: us-central1-docker.pkg.dev/employee-rbac/springboot-repo/employee-api:v1

        ports:

        - containerPort: 8080